language: java

jdk:
    - openjdk8

env:
    global:
        - CODECOV_TOKEN="f9785a90-d5af-416f-ad9e-5f4883f41041"

install: true

script: "./gradlew testReport"

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
    only:
        - master

notifications:
    slack: cheese-dev:JXKSTVY4wHsMPbJi2uoKtyxs
    email: false