language: java

jdk:
  - openjdk8

#env:
#  global:
#    - CODECOV_TOKEN = d116be9b-435a-42f3-a4c2-224be876d3f9

install: true

script: "./gradlew testReport"

cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

#after_success:
# - mvn clean cobertura:cobertura coveralls:report
# - bash <(curl -s https://codecov.io/bash)

branches:
 only:
    - master

notifications:
  slack: cheese-dev:JXKSTVY4wHsMPbJi2uoKtyxs
  email: false